import type { Metadata } from "next";
import { Inter, Diplomata_SC, Bellefair } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

const diplomata = Diplomata_SC({
  variable: "--font-diplomata-sc",
  subsets: ["latin"],
  weight: ["400"],
});

const fontHeading = Bellefair({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Mohamed Sanjeed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          diplomata.variable,
          inter.className,
          fontHeading.variable,
          "antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}
