import type { Metadata } from "next";
import { Raleway, Honk, Oswald } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

const honk = Honk({
  variable: "--font-honk",
  subsets: ["latin"],
  weight: ["400"],
});

const fontHeading = Oswald({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Mohamed Sanjeed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          honk.variable,
          raleway.className,
          fontHeading.variable,
          "antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}
